---
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu20
    - MOLECULE_DISTRO: ubuntu18
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker yamllint

script:
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
