---

- name: check if murmurd is already installed.
  stat:
    path: /usr/sbin/murmurd
  register: murmurd_installed

- name: ensure required packages are present
  apt:
    pkg: mumble-server

- name: generate the Murmur config file
  template:
    src: "mumble-server.ini.j2"
    dest: "/etc/mumble-server.ini"
    owner: root
    group: mumble-server
    mode: 0640
  notify: restart murmur

- name: set the superuser password [not idempodent]
  shell: murmurd -ini /etc/mumble-server.ini -supw "{{ murmur_superuser_password }}"
  when: murmurd_installed.stat.exists == false
