---
scenario:
  name: default
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
provisioner:
  name: ansible
  become: True
lint:
  name: yamllint
  enabled: True
